# fly.toml app configuration file generated for env-leaker-v-q-ig on 2026-05-25T20:22:53Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'env-leaker-v-q-ig'
primary_region = 'ams'

[env]
  PORT = 8080

[http_service]
  internal_port = 8080
  force_https = false
  auto_stop_machines = 'suspend'
  auto_start_machines = false
  min_machines_running = 3
  processes = ['app', 'duplicado']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 4
  memory_mb = 2048
  processes = ['app']
  size = 'shared-cpu-4x'

[processes]
  app = 'node server.js'
  duplicado = ''
