# fly.toml app configuration file generated for env-leaker-v-q-ig on 2026-05-25T20:53:54Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'env-leaker-v-q-ig'
primary_region = 'ams'

[env]
  PORT = 8080

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 2
  processes = ['app', 'duplicado']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
  processes = ['app']
  size = 'shared-cpu-1x'

[processes]
  app = ''
  duplicado = 'node server.js'
