# fly.toml app configuration file generated for env-leaker-v-q-ig on 2026-05-25T19:51:49Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'env-leaker-v-q-ig'
primary_region = 'ams'

[env]
  PORT = 8080

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app', "duplicado"]

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 4
  memory_mb = 2048
  processes = ['app']
  size = 'shared-cpu-4x'

[processes]
  app = 'node server.js'
  duplicado = ""
